## 06 形状/文字绘制

- 1. 图形
- 2. 文字

---


#### 1. 图形
线段，矩形，圆形

In [1]:
import numpy as np
import cv2

In [4]:
# —— line ——

newImageInfo = (500, 500, 3)
dst = np.zeros(newImageInfo, np.uint8)
# 绘制线段 1 dstImage 2 begin 3 end 4 color
cv2.line(dst, (100, 100), (400, 400), (0, 0, 255))

# 5 lineWidth
cv2.line(dst, (100, 200), (400, 200), (0, 255, 255), 20)

# 6 lineType  cv2.LINE_AA的线条更光滑
cv2.line(dst, (100, 300), (400, 300), (0, 255, 255), 20, cv2.LINE_AA)

# 三角形
cv2.line(dst, (200, 150), (50, 250), (25, 100, 40), 5)
cv2.line(dst, (50, 250), (400, 380), (25, 100, 40), 5)
cv2.line(dst, (400, 380), (200, 150), (25, 100, 40), 5)

cv2.imshow('image', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [35]:
# —— 矩形圆形etc ——

newImageInfo = (500, 500, 3)
dst = np.zeros(newImageInfo, np.uint8)

# 1 dst 2 左上角 3 右下角 4 颜色 5 (-1):fill or (>0):lineW()
cv2.rectangle(dst, (10, 100), (100, 200), (100, 50, 120), -1)
cv2.rectangle(dst, (110, 100), (200, 200), (90, 140, 123), 2)

# 2 center 3 r

cv2.circle(dst, (250, 250), 50, (120, 140, 50), 2)

# 2 椭圆圆心 3 长短轴  4 angle 5 begin 6 end 7 (-1):fill or (>0):lineW()
cv2.ellipse(dst, (400, 250), (80, 30), 0, 0, 360, (90, 80, 180), 2)

# 任意多边形
points = np.array([[150, 50], [140, 140], [200, 170], [250, 250], [150, 50]],
                  np.int32)
print(points.shape)
print(points)
points = points.reshape((-1, 1, 2))
print(points.shape)
print(points)
cv2.polylines(dst,[points],True,(145,80,20),2)

cv2.imshow('image', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

(5, 2)
[[150  50]
 [140 140]
 [200 170]
 [250 250]
 [150  50]]
(5, 1, 2)
[[[150  50]]

 [[140 140]]

 [[200 170]]

 [[250 250]]

 [[150  50]]]


In [2]:
# 这是个用来理解reshape()的例子 
# 上面的 points.shape=(5,1,2)
# 这个是 (1,5,2)  放入polylines也没错
# anyway 要把一个坐标当作一个元素来看
newImageInfo = (500, 500, 3)
dst = np.zeros(newImageInfo, np.uint8)
points = np.array([[[150, 50], [140, 140], [200, 170], [250, 250], [150, 50]]],
                  np.int32)
print(points.shape)
print(points)

cv2.polylines(dst,[points],True,(145,80,20),2)

cv2.imshow('image', dst)
cv2.waitKey(0)
cv2.destroyAllWindows()

(1, 5, 2)
[[[150  50]
  [140 140]
  [200 170]
  [250 250]
  [150  50]]]


#### 2. 文字 图片绘制
---


In [3]:
import numpy as np
import cv2

In [ ]:
img=cv2.imread('Album.jpg',1)
font=cv2.FONT_HERSHEY_SIMPLEX
cv2.rectangle(img,(200,100),(500,400),(0,255,0),3)

# 1 img 2 文字内容 3 坐标 4 5 字体大小 6 color 7 lineWidth 8 LineType
cv2.putText(img,'this is flow',(100,300),font,1,(200,100,255),2,cv2.LINE_AA)
cv2.imshow('src',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# pic+pic*0.2
img=cv2.imread('Album.jpg',1)
imgInfo=img.shape
height=int(imgInfo[0]*0.2)
width=int(imgInfo[1]*0.2)
imgResize=cv2.resize(img,(width,height))
for i in range(0,height):
    for j in range(0,width):
        img[i+200,j+350]=imgResize[i,j]
        
cv2.imshow('src',img)
cv2.waitKey(0)
cv2.destroyAllWindows()